### ISSUE TITLE
New blog location

### ISSUE THREAD

**Issue by hinojosachapel** [martinkearn/Content#3]
Today I was re-reading your excellent article "Bot Framework V4: What I learnt in 4 days in July 2018" on the Microsoft site and, somehow, I updated the webpage and the article content disappeared. Instead a new link was showed, pointing to the new location in your own site. It was visually painful because of the colour scheme change, but fortunately we can still read the article black on white on your GitHub site. Great job!

**Comment by martinkearn** [comment]
Thanks for the feedback, you're not the first one to comment on the styling for articles on my website .... it is on my list to fix ;)

**Comment by martinkearn** [comment]
This has now been resolved. I've largely adopted GitHub styling for articles
